// <auto-generated />
using FxMovies.ImdbDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace ImdbDB.Migrations
{
    [DbContext(typeof(ImdbDbContext))]
    partial class ImdbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("FxMovies.ImdbDB.Movie", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PrimaryTitle");

                    b.Property<int?>("Rating");

                    b.Property<int?>("Votes");

                    b.Property<int?>("Year");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTitle", "Year");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
