name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    # - name: Deploy to Server
    #   uses: easingthemes/ssh-deploy@main
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
    #     ARGS: "-rltgoDzvO --delete"
    #     SOURCE: "FxMovieAlert/bin/Release/net5.0/publish/"
    #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
    #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
    #     TARGET: ${{ secrets.REMOTE_TARGET }}
    #     EXCLUDE: "/appsettings.*, /wwwroot/images/cache/*"
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: whoami